async function InsertSampleData(db) {
  try {
    // Check if data already exists in the database
    const existingCampuses = await db.Campus.findAll();
    if (existingCampuses.length > 0) {
      console.log("\n\n\n\nSample data already exists, skipping insertion.\n\n\n\n");
      return; // Exit the function if sample data is already present
    }
        
    // Insert sample campuses
    const campuses = await db.Campus.bulkCreate([
      { campusName: "Mandaue Campus", campusAddress: "AS Fortuna Street, Mandaue City 6014, Metro Cebu, Philippines" },
      { campusName: "Cebu Campus", campusAddress: "B. Benedicto St, Cebu City, 6000 Cebu, Philippines" }
    ], { returning: true }); // Returning allows us to use the created campus IDs for the next inserts

    // Insert sample semesters 
    const semesters = await db.Semester.bulkCreate([
      { campus_id: campuses[1].campus_id, semesterName: "1st Semester", schoolYear: "2024-2025", isActive: false },
      { campus_id: campuses[1].campus_id, semesterName: "2nd Semester", schoolYear: "2024-2025", isActive: true },
      { campus_id: campuses[1].campus_id, semesterName: "Summer", schoolYear: "2024-2025", isActive: false },
      { campus_id: campuses[0].campus_id, semesterName: "1st Semester", schoolYear: "2024-2025", isActive: false },
      { campus_id: campuses[0].campus_id, semesterName: "2nd Semester", schoolYear: "2024-2025", isActive: true },
      { campus_id: campuses[0].campus_id, semesterName: "Summer", schoolYear: "2024-2025", isActive: false }
    ]);

    // Insert sample departments
    const departments = await db.Department.bulkCreate([
      { campus_id: campuses[0].campus_id, departmentCode: "CCS", departmentName: "College of Computer Studies", departmentDean: "Prof. Gene Paul Cueva, MBA, MSIT" },
      { campus_id: campuses[0].campus_id, departmentCode: "CBM", departmentName: "College of Business and Management", departmentDean: "Dr. Jaypee Y. Zoilo, MBA" },
      { campus_id: campuses[1].campus_id, departmentCode: "CCS", departmentName: "College of Computer Studies", departmentDean: "test" },
      { campus_id: campuses[1].campus_id, departmentCode: "CBM", departmentName: "College of Business and Management", departmentDean: "test" },
      { campus_id: campuses[0].campus_id, departmentCode: "CEA", departmentName: "College of Education and Arts", departmentDean: "Dr. Johner D. Montegrande" },
      { campus_id: campuses[0].campus_id, departmentCode: "COE", departmentName: "College of Engineering", departmentDean: "Dr. Nimfa Ramirez" },
      { campus_id: campuses[1].campus_id, departmentCode: "CEA", departmentName: "College of Education and Arts", departmentDean: "test" },
    ]);

    const employees = await db.Employee.bulkCreate([
      { campus_id: null, department_id: null, title: "SuperAdmin", firstName: "John Robert", middleName: "Libaton", lastName: "Maizo", role: ["SuperAdmin"], qualifications: null, gender: "Male", address: "C.D. Seno St., Tipolo, Mandaue City", contactNumber: "09321146580", birthDate: "2002-07-30"},

      { campus_id: campuses[0].campus_id, department_id: null, title: "Administrator", firstName: "John Robert", middleName: "Dope", lastName: "Gwapo", role: ["Admin"], qualifications: null, gender: "Male", address: "C.D. Seno St., Tipolo, Mandaue City", contactNumber: "09321146580", birthDate: "2002-07-30"},

      { campus_id: campuses[1].campus_id, department_id: null, title: "Administrator", firstName: "Juan", middleName: "Cingko", lastName: "Makabugto", role: ["Admin"], qualifications: null, gender: "Male", address: "Lahug, Cebu City", contactNumber: "09485324123", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: null, title: "Mr.", firstName: "Yoshihisa", middleName: null, lastName: "Iguchi", role: ["MIS"], qualifications: null, gender: "Male", address: "1152 Poplar Chase Lane", contactNumber: "09485324123", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: null, title: "Mr.", firstName: "Registrar", middleName: "Gwapo", lastName: "Choyins", role: ["Registrar"], qualifications: null, gender: "Male", address: "Registrar, Mandaue City", contactNumber: "09485324123", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: null, title: "Mr.", firstName: "Data", middleName: "Gwapo", lastName: "Center", role: ["DataCenter"], qualifications: null, gender: "Male", address: "Data Center, Mandaue City", contactNumber: "09485324123", birthDate: "1999-05-28"},


      { campus_id: campuses[0].campus_id, department_id: departments[0].department_id, title: "Prof.", firstName: "Gene Paul", middleName: "Rubia", lastName: "Cueva", role: ["Dean, Professor"], qualifications: [{abbreviation: "MBA", meaning: "Master of Business Administration"}, {abbreviation: "MSIT", meaning: "Master of Science in Information Technology"}], gender: "Male", address: "Cordova, Cebu", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: departments[1].department_id, title: "Dr.", firstName: "Jaypee", middleName: "Y", lastName: "Zoilo", role: ["Dean, Professor"], qualifications: [{abbreviation: "MBA", meaning: "Master of Business Administration"}], gender: "Male", address: "Lapu-Lapu City", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: departments[4].department_id, title: "Dr.", firstName: "Johner", middleName: "D", lastName: "Montegrande", role: ["Dean, Professor"], qualifications: null, gender: "Male", address: "Cebu", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: departments[5].department_id, title: "Dr.", firstName: "Nimfa", middleName: null, lastName: "Ramirez", role: ["Dean, Professor"], qualifications: null, gender: "Female", address: "Cebu", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: null, title: "Mrs.", firstName: "Leah", middleName: "B", lastName: "Artap", role: ["Accounting"], qualifications: [{abbreviation: "CPA", meaning: "Certified Public Accountant"}], gender: "Female", address: "Minglanilla City", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: departments[1].department_id, title: "Mr.", firstName: "Kervy", middleName: "C", lastName: "Conde", role: ["Professor, Instructor"], qualifications: [{abbreviation: "MBA", meaning: "Master of Business Administration"}], gender: "Male", address: "Lapu-Lapu City", contactNumber: "09123456789", birthDate: "1999-05-28"},

      { campus_id: campuses[0].campus_id, department_id: departments[0].department_id, title: "Ms.", firstName: "Leny", middleName: "B", lastName: "Yamillo", role: "Professor, Instructor, Gwapo", qualifications: [{abbreviation: "DPA", meaning: "Doctor of Public Administration"}, {abbreviation: "LPT", meaning: "Licensed Professional Teacher"}], gender: "Female", address: "Lapu-Lapu City", contactNumber: "09123456789", birthDate: "1999-05-28"},
      
      { campus_id: campuses[0].campus_id, department_id: departments[4].department_id, title: "Mr.", firstName: "John", middleName: "Gwapo", lastName: "Doe", role: "Professor, Instructor", qualifications: [{abbreviation: "LPT", meaning: "Licensed Professional Teacher"}], gender: "Male", address: "C.D. Seno St., Tipolo, Mandaue City", contactNumber: "09123456789", birthDate: "1999-05-28"},
    ]);

    // Insert sample programs
    const programs = await db.Program.bulkCreate([
      {department_id: departments[0].department_id, programCode: "BSIT", programDescription: "Bachelor of Science in Information Technology"},
      {department_id: departments[2].department_id, programCode: "BSIT", programDescription: "Bachelor of Science in Information Technology"},
      {department_id: departments[1].department_id, programCode: "BSBA-HRM", programDescription: "Bachelor of Science in Business Administration major in Human Resource Management"},
      {department_id: departments[1].department_id, programCode: "BSBA-MM", programDescription: "Bachelor of Science in Business Administration major in Marketing Management"},
      {department_id: departments[1].department_id, programCode: "BSHM", programDescription: "Bachelor of Science in Hospitality Management"},
      {department_id: departments[1].department_id, programCode: "BSA", programDescription: "Bachelor of Science in Accountancy"},
      {department_id: departments[3].department_id, programCode: "BSBA-MM", programDescription: "Bachelor of Science in Business Administration major in Marketing Management"},
      {department_id: departments[3].department_id, programCode: "BSA", programDescription: "Bachelor of Science in Accountancy"},
      {department_id: departments[4].department_id, programCode: "BEED", programDescription: "Bachelor of Elementary Education major in General Content"},
      {department_id: departments[4].department_id, programCode: "BSED", programDescription: "Bachelor of Secondary Education major in English"},
      {department_id: departments[4].department_id, programCode: "BA-COMM", programDescription: "Bachelor of Arts in Communication"},
      {department_id: departments[5].department_id, programCode: "BSME", programDescription: "Bachelor of Science in Mechanical Engineering"},
      {department_id: departments[5].department_id, programCode: "BSCE", programDescription: "Bachelor of Science in Civil Engineering"},
      {department_id: departments[5].department_id, programCode: "BSEE", programDescription: "Bachelor of Science in Electrical Engineering"},
      {department_id: departments[5].department_id, programCode: "BSIE", programDescription: "Bachelor of Science in Industrial Engineering"},
      {department_id: departments[3].department_id, programCode: "BSTM", programDescription: "Bachelor of Science in Tourism Management"},
      {department_id: departments[6].department_id, programCode: "BSED", programDescription: "Bachelor of Secondary Education major in English"},
    ])

    const courseinfos = await db.CourseInfo.bulkCreate([
      { campus_id: campuses[0].campus_id, courseCode: "RIZAL", courseDescription: "Rizal's Life & Works", unit: 3, department_id: null},
      { campus_id: campuses[1].campus_id, courseCode: "RIZAL", courseDescription: "Rizal's Life & Works", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "ARTHUM", courseDescription: "Arts & Humanities", unit: 3, department_id: null},
      { campus_id: campuses[1].campus_id, courseCode: "ARTHUM", courseDescription: "Arts & Humanities", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "FIL211", courseDescription: "Pagtuturo ng Filipino sa Elementarya 1 (Estruktura at Gamit ng Wikang Filipino)", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[1].campus_id, courseCode: "FIL211", courseDescription: "Pagtuturo ng Filipino sa Elementarya 1 (Estruktura at Gamit ng Wikang Filipino)", unit: 3, department_id: departments[6].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ENGL211", courseDescription: "Teaching English in the Elem. Grades (Language Arts)", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "LIT1", courseDescription: "Philippine Literature", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "STS", courseDescription: "Science, Technology & Society", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "UTS", courseDescription: "Understanding the Self", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "NSTP1", courseDescription: "National Service Training Prog. 1", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "CW", courseDescription: "The Contemporary World", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "ECE111", courseDescription: "Basic Electronics - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ECE111L", courseDescription: "Basic Electronics - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EE201", courseDescription: "Basic Electrical Engineering - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EE201L", courseDescription: "Basic Electrical Engineering - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ES211", courseDescription: "Statics of Rigid Bodies", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ES212", courseDescription: "Computer Fund. & Programming 1 - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ES213", courseDescription: "Environmental Science", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MATH214", courseDescription: "Differential Equation", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ME211", courseDescription: "Thermodynamics 1", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "PE3", courseDescription: "Individual/Dual Sports", unit: 2, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "CE411", courseDescription: "Principles of Steel Design - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE411L", courseDescription: "Principles of Steel Design - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE412", courseDescription: "Principles of Reinforced/Prestessesd Concrete - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE412L", courseDescription: "Principles of Reinforced/Prestessesd Concrete - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE413", courseDescription: "CE Project 1 - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE413L", courseDescription: "CE Project 1 - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE414", courseDescription: "Principles of Transportation Engineering", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE415", courseDescription: "Construction Methods & Project Management", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE416", courseDescription: "Refresher Course 2", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ES411", courseDescription: "Engineering Management", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "PCS1", courseDescription: "Project Construction and Management", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "PCS2", courseDescription: "Construction Cost Engineering", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE400", courseDescription: "On-the-Job Training (240 Hours) - Lec", unit: 2, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "CE400L", courseDescription: "On-the-Job Training (240 Hours) - Lab", unit: 1, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EE400", courseDescription: "On-the-Job Training (240 Hours)", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IE400", courseDescription: "On-the-Job Training (240 Hours)", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ME400", courseDescription: "On-the-Job Training (240 Hours)", unit: 3, department_id: departments[5].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FS1", courseDescription: "Field Study 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FS2", courseDescription: "Field Study 2", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "RGEC2", courseDescription: "Review on Professional Education Courses", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM411", courseDescription: "Communication Planning", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM412", courseDescription: "Communication Management", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "THESIS1", courseDescription: "Social Project 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC311", courseDescription: "Assessment in Learning 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC312", courseDescription: "Technology for Teaching and Learning 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC313", courseDescription: "Facilitating Learner-Centered Teaching", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "LIT313", courseDescription: "Survey of Phil. Literature in English", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "LIT314", courseDescription: "Survey of Afro-Asian Literature", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "LIT315", courseDescription: "Survey of English & American Literature", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "LIT316", courseDescription: "Contemporary, Popular & Emergent Literature", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "SOCPHIL", courseDescription: "Social Science and Philosophy", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM111", courseDescription: "Intro. to Communication Media", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM210", courseDescription: "Development Communication", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FIL3", courseDescription: "Masining na Pagpapahayag", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MST", courseDescription: "Mathematics, Science & Technology", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EL100", courseDescription: "Introduction to Linguistics", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EL101", courseDescription: "Language, Culture & Society", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EL102", courseDescription: "Structures of English", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FIL1", courseDescription: "Wikang Filipino", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "HIST", courseDescription: "Readings in Philippine History", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "PURCOM", courseDescription: "Purposive Communication", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "CEL311", courseDescription: "Public Information Principles & Practices", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM311", courseDescription: "Communication Theory", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "COM312", courseDescription: "Comm. Media Laws & Ethics", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IPO310", courseDescription: "Public Relations Principles and Practices", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "PUBAD", courseDescription: "Public Administration", unit: 3, department_id: departments[1].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "STAT", courseDescription: "Statistics & Probability", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC211", courseDescription: "The Teaching Profession", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ELT214", courseDescription: "Teaching & Assessment of Lit.", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ELT215", courseDescription: "Teaching & Assessment of the Macroskills", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ELT216", courseDescription: "Teaching & Assessment of theGrammar", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ELT217", courseDescription: "Speech & Theater Arts", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ETHICS", courseDescription: "Ethics", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "MATHWORLD", courseDescription: "Mathematics in the Modern World", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "ARTS100", courseDescription: "Teaching Arts in the Elem.", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC311", courseDescription: "Assessment in Learning 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC312", courseDescription: "Technology for Teaching and Learning 1", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC313", courseDescription: "Facilitating Learner-Centered Teaching", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MUSIC100", courseDescription: "Teaching Music in the Elementary Grades", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "RES100", courseDescription: "Research in Education", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "TLE311", courseDescription: "Edukasyong Pantahanan at Pangkabuhayan", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "EDUC211", courseDescription: "The Teaching Profession", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MATH211", courseDescription: "Teaching Math in the Primary Grades", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "SCI211", courseDescription: "Teaching Science in Elementary Grades (Biology & Chemistry)", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "SSC211", courseDescription: "Teaching Social Studies in the Elementary Grades (Phil. History & Government)", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "VED100", courseDescription: "Good Manners and Right Conduct", unit: 3, department_id: departments[4].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FS", courseDescription: "Feasibility Study", unit: 3, department_id: departments[1].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "HRDM12", courseDescription: "Special Topics in Human Management", unit: 3, department_id: departments[1].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FIL2", courseDescription: "Panitikan ng Pilipinas", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "NSTP2", courseDescription: "National Service Traning Prog. 2", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "IT110", courseDescription: "Introduction to Computing (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT110L", courseDescription: "Introduction to Computing (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT111", courseDescription: "Computer Programming I (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT111L", courseDescription: "Computer Programming I (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MATHPREP", courseDescription: "Pre Calculus for Non-STEM", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "PE1", courseDescription: "Wellness & Fitness", unit: 2, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "IT120", courseDescription: "Discrete Structures", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT121", courseDescription: "Computer Programming II (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT121L", courseDescription: "Computer Programming II (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "PE2", courseDescription: "Self Defense", unit: 2, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "IT210", courseDescription: "Data Structures & Algorithm (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT210L", courseDescription: "Data Structures & Algorithm (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT211", courseDescription: "Web Design & Development (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT211L", courseDescription: "Web Design & Development (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT212", courseDescription: "Digital Logic Design (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT212L", courseDescription: "Digital Logic Design (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT213", courseDescription: "PC Assembly & Troubleshooting (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT213L", courseDescription: "PC Assembly & Troubleshooting (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ARTAPP", courseDescription: "Art Appreciation", unit: 3, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "IT220", courseDescription: "Object-Oriented Programming (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT220L", courseDescription: "Object-Oriented Programming (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT221", courseDescription: "Networking (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT221L", courseDescription: "Networking (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT222", courseDescription: "Database Management (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT222L", courseDescription: "Database Management (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ACCTG", courseDescription: "Fundamentals of Accounting", unit: 6, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "PE4", courseDescription: "Team Sports", unit: 2, department_id: null},
      { campus_id: campuses[0].campus_id, courseCode: "IT223", courseDescription: "Information Management", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITTEL1", courseDescription: "IT Track Elective 1 - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITTEL1L", courseDescription: "IT Track Elective 1 - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "FILIT", courseDescription: "The Philippine Society in the IT Era", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT310", courseDescription: "Applications Development and Emerging Technologies (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT310L", courseDescription: "Applications Development and Emerging Technologies (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT311", courseDescription: "Operating Systems (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT311L", courseDescription: "Operating Systems (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT312", courseDescription: "Human Computer Interaction (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT312L", courseDescription: "Human Computer Interaction (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC1", courseDescription: "IT Elective I (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC1L", courseDescription: "IT Elective I (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITTEL2", courseDescription: "IT Track Elective II (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITTEL2L", courseDescription: "IT Track Elective II (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "TECHNO", courseDescription: "Technopreneurship (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "TECHNOL", courseDescription: "Technopreneurship (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT320", courseDescription: "Systems Analysis & Design (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT320L", courseDescription: "Systems Analysis & Design (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT321", courseDescription: "Information Assurance & Security (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT321L", courseDescription: "Information Assurance & Security (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT322", courseDescription: "Systems Integration & Architecture (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT322L", courseDescription: "Systems Integration & Architecture (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MMG", courseDescription: "Marketing Media Gamification (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "MMGL", courseDescription: "Marketing Media Gamification (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC2", courseDescription: "IT Elective II (Lec)", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC2L", courseDescription: "IT Elective II (Lab)", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT323", courseDescription: "Capstone Project 1 - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT323L", courseDescription: "Capstone Project 1 - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT324", courseDescription: "Social Issues & Professional Practices", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT325", courseDescription: "Quantitative Methods", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT410", courseDescription: "Capstone Project II - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT410L", courseDescription: "Capstone Project II - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT411", courseDescription: "Integrative Programming & Technologies - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT411L", courseDescription: "Integrative Programming & Technologies - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT412", courseDescription: "Systems Administration & Maintenance - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT412L", courseDescription: "Systems Administration & Maintenance - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC3", courseDescription: "IT Elective III - Lec", unit: 2, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "ITELEC3L", courseDescription: "IT Elective III - Lab", unit: 1, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "IT420", courseDescription: "IT Seminars & Tours", unit: 3, department_id: departments[0].department_id},
      { campus_id: campuses[0].campus_id, courseCode: "OJT", courseDescription: "On the Job Training (500 Hours)", unit: 6, department_id: departments[0].department_id},
    ])

    // const programcourses = await db.ProgramCourse.bulkCreate([
    //   { program_id: "1", course_id: "1", },
    //   { program_id: "1", course_id: "3", },
    //   { program_id: "1", course_id: "8", },
    //   { program_id: "1", course_id: "9", },
    //   { program_id: "1", course_id: "10", },
    //   { program_id: "1", course_id: "11", },
    //   { program_id: "1", course_id: "12", },
    //   { program_id: "1", course_id: "13", },
    //   { program_id: "1", course_id: "23", },
    //   { program_id: "1", course_id: "62", },
    //   { program_id: "1", course_id: "70", },
    //   { program_id: "1", course_id: "76", },
    //   { program_id: "1", course_id: "77", },
    //   { program_id: "1", course_id: "92", },
    //   { program_id: "1", course_id: "93", },
    //   { program_id: "1", course_id: "96", },
    //   { program_id: "1", course_id: "97", },
    //   { program_id: "1", course_id: "102", },
    //   { program_id: "1", course_id: "111", },
    //   { program_id: "1", course_id: "118", },
    //   { program_id: "1", course_id: "120", },
    //   { program_id: "1", course_id: "94", },
    //   { program_id: "1", course_id: "95", },
    //   { program_id: "1", course_id: "99", },
    //   { program_id: "1", course_id: "100", },
    //   { program_id: "1", course_id: "101", },
    //   { program_id: "1", course_id: "103", },
    //   { program_id: "1", course_id: "104", },
    //   { program_id: "1", course_id: "105", },
    //   { program_id: "1", course_id: "106", },
    //   { program_id: "1", course_id: "107", },
    //   { program_id: "1", course_id: "108", },
    //   { program_id: "1", course_id: "109", },
    //   { program_id: "1", course_id: "110", },
    //   { program_id: "1", course_id: "112", },
    //   { program_id: "1", course_id: "113", },
    //   { program_id: "1", course_id: "114", },
    //   { program_id: "1", course_id: "115", },
    //   { program_id: "1", course_id: "116", },
    //   { program_id: "1", course_id: "117", },
    //   { program_id: "1", course_id: "121", },
    //   { program_id: "1", course_id: "122", },
    //   { program_id: "1", course_id: "123", },
    //   { program_id: "1", course_id: "124", },
    //   { program_id: "1", course_id: "125", },
    //   { program_id: "1", course_id: "126", },
    //   { program_id: "1", course_id: "127", },
    //   { program_id: "1", course_id: "128", },
    //   { program_id: "1", course_id: "129", },
    //   { program_id: "1", course_id: "130", },
    //   { program_id: "1", course_id: "131", },
    //   { program_id: "1", course_id: "132", },
    //   { program_id: "1", course_id: "133", },
    //   { program_id: "1", course_id: "134", },
    //   { program_id: "1", course_id: "135", },
    //   { program_id: "1", course_id: "138", },
    //   { program_id: "1", course_id: "139", },
    //   { program_id: "1", course_id: "140", },
    //   { program_id: "1", course_id: "141", },
    //   { program_id: "1", course_id: "142", },
    //   { program_id: "1", course_id: "143", },
    //   { program_id: "1", course_id: "144", },
    //   { program_id: "1", course_id: "145", },
    //   { program_id: "1", course_id: "146", },
    //   { program_id: "1", course_id: "147", },
    //   { program_id: "1", course_id: "148", },
    //   { program_id: "1", course_id: "149", },
    //   { program_id: "1", course_id: "150", },
    //   { program_id: "1", course_id: "151", },
    //   { program_id: "1", course_id: "152", },
    //   { program_id: "1", course_id: "153", },
    //   { program_id: "1", course_id: "154", },
    //   { program_id: "1", course_id: "155", },
    //   { program_id: "1", course_id: "156", },
    //   { program_id: "1", course_id: "157", },
    //   { program_id: "1", course_id: "158", },
    //   { program_id: "1", course_id: "159", },
    //   { program_id: "1", course_id: "160", },
    //   { program_id: "1", course_id: "161",  }
    // ])

    const prospectus = await db.Prospectus.bulkCreate([
      {program_id: 1, prospectusName: "BSIT Prospectus 1", prospectusDescription: "Revised Curriculum Effective School Year 2018-2019"}
    ])

    const prospectusSubjects = await db.ProspectusSubject.bulkCreate([
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 10,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 11,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 61,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 76,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 93,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 94,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 95,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 96,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 97,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "1st Semester",
        course_id: 98,
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 62,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 63,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 91,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 92,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 99,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 100,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 101,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "First Year",
        semesterName: "2nd Semester",
        course_id: 102,
        createdAt: "2024-10-13 13:19:09",
        updatedAt: "2024-10-13 13:19:09",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 12,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 22,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 103,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 104,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 105,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 106,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 107,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 108,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 109,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 110,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "1st Semester",
        course_id: 111,
        createdAt: "2024-10-13 13:19:16",
        updatedAt: "2024-10-13 13:19:16",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 9,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 75,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 112,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 113,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 114,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 115,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 116,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 117,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 118,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "2nd Semester",
        course_id: 119,
        createdAt: "2024-10-13 13:19:23",
        updatedAt: "2024-10-13 13:19:23",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "Summer",
        course_id: 120,
        createdAt: "2024-10-13 13:19:31",
        updatedAt: "2024-10-13 13:19:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "Summer",
        course_id: 121,
        createdAt: "2024-10-13 13:19:31",
        updatedAt: "2024-10-13 13:19:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "Summer",
        course_id: 122,
        createdAt: "2024-10-13 13:19:31",
        updatedAt: "2024-10-13 13:19:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Second Year",
        semesterName: "Summer",
        course_id: 123,
        createdAt: "2024-10-13 13:19:31",
        updatedAt: "2024-10-13 13:19:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 69,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 124,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 125,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 126,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 127,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 128,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 129,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 130,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 131,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 132,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 133,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 134,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "1st Semester",
        course_id: 135,
        createdAt: "2024-10-13 13:21:57",
        updatedAt: "2024-10-13 13:21:57",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 136,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 137,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 138,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 139,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 140,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 141,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 142,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 144,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "2nd Semester",
        course_id: 145,
        createdAt: "2024-10-13 13:30:04",
        updatedAt: "2024-10-13 13:30:04",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "Summer",
        course_id: 146,
        createdAt: "2024-10-13 13:31:31",
        updatedAt: "2024-10-13 13:31:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "Summer",
        course_id: 147,
        createdAt: "2024-10-13 13:31:31",
        updatedAt: "2024-10-13 13:31:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "Summer",
        course_id: 148,
        createdAt: "2024-10-13 13:31:31",
        updatedAt: "2024-10-13 13:31:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Third Year",
        semesterName: "Summer",
        course_id: 149,
        createdAt: "2024-10-13 13:31:31",
        updatedAt: "2024-10-13 13:31:31",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 1,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 150,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 151,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 152,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 153,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 154,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 155,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 156,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "1st Semester",
        course_id: 157,
        createdAt: "2024-10-13 13:34:56",
        updatedAt: "2024-10-13 13:34:56",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "2nd Semester",
        course_id: 158,
        createdAt: "2024-10-13 13:36:55",
        updatedAt: "2024-10-13 13:36:55",
      },
      {
        prospectus_id: 1,
        yearLevel: "Fourth Year",
        semesterName: "2nd Semester",
        course_id: 159,
        createdAt: "2024-10-13 13:36:55",
        updatedAt: "2024-10-13 13:36:55",
      },
    ])

    const prospectusPreRequisite = await db.PreRequisite.bulkCreate([
      {
        prospectus_subject_id: 18,
        course_id: 98,
      },
      {
        prospectus_subject_id: 15,
        course_id: 97,
      },
      {
        prospectus_subject_id: 16,
        course_id: 95,
      },
      {
        prospectus_subject_id: 17,
        course_id: 96,
      },
      {
        prospectus_subject_id: 23,
        course_id: 100,
      },
      {
        prospectus_subject_id: 24,
        course_id: 101,
      },
      {
        prospectus_subject_id: 25,
        course_id: 99,
      },
      {
        prospectus_subject_id: 26,
        course_id: 99,
      },
      {
        prospectus_subject_id: 27,
        course_id: 93,
      },
      {
        prospectus_subject_id: 28,
        course_id: 94,
      },
      {
        prospectus_subject_id: 20,
        course_id: 102,
      },
      {
        prospectus_subject_id: 21,
        course_id: 99,
      },
      {
        prospectus_subject_id: 22,
        course_id: 99,
      },
      {
        prospectus_subject_id: 36,
        course_id: 103,
      },
      {
        prospectus_subject_id: 37,
        course_id: 104,
      },
      {
        prospectus_subject_id: 39,
        course_id: 22,
      },
      {
        prospectus_subject_id: 32,
        course_id: 103,
      },
      {
        prospectus_subject_id: 33,
        course_id: 104,
      },
      {
        prospectus_subject_id: 34,
        course_id: 93,
      },
      {
        prospectus_subject_id: 35,
        course_id: 94,
      },
      {
        prospectus_subject_id: 41,
        course_id: 116,
      },
      {
        prospectus_subject_id: 42,
        course_id: 117,
      },
      {
        prospectus_subject_id: 44,
        course_id: 97,
      },
      {
        prospectus_subject_id: 47,
        course_id: 114,
      },
      {
        prospectus_subject_id: 48,
        course_id: 115,
      },
      {
        prospectus_subject_id: 45,
        course_id: 112,
      },
      {
        prospectus_subject_id: 46,
        course_id: 113,
      },
      {
        prospectus_subject_id: 49,
        course_id: 112,
      },
      {
        prospectus_subject_id: 50,
        course_id: 113,
      },
      {
        prospectus_subject_id: 53,
        course_id: 121,
      },
      {
        prospectus_subject_id: 54,
        course_id: 122,
      },
      {
        prospectus_subject_id: 57,
        course_id: 120,
      },
      {
        prospectus_subject_id: 58,
        course_id: 120,
      },
      {
        prospectus_subject_id: 59,
        course_id: 124,
      },
      {
        prospectus_subject_id: 60,
        course_id: 125,
      },
      {
        prospectus_subject_id: 64,
        course_id: 130,
      },
      {
        prospectus_subject_id: 65,
        course_id: 131,
      },
      {
        prospectus_subject_id: 69,
        course_id: 69,
      },
      {
        prospectus_subject_id: 71,
        course_id: 146,
      },
      {
        prospectus_subject_id: 72,
        course_id: 147,
      },
      {
        prospectus_subject_id: 75,
        course_id: 148,
      },
      {
        prospectus_subject_id: 76,
        course_id: 148,
      },
      {
        prospectus_subject_id: 73,
        course_id: 138,
      },
      {
        prospectus_subject_id: 74,
        course_id: 139,
      },
    ])

    const buildingStructres = await db.BuildingStructure.bulkCreate([
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", isBuilding: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", isFloor: true},
      { campus_id: campuses[1].campus_id, buildingName: "Cebu Building", isBuilding: true},
      { campus_id: campuses[1].campus_id, buildingName: "Cebu Building", floorName: "2nd Floor", isFloor: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "201", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", isFloor: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "CL-1", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "CL-2", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "301", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "303", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "305", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "306", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "307", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "308", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "309", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "310", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "311", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "312", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "313", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "314 (Amphitheatre)", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "315", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "316", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "317", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "318", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "319", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "320", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "321", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "322", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "323", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "324", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "325", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "3rd Floor", roomName: "326", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "202", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "203", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "204", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "205", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "206", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "207", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "208", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "209", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "210", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "211", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "212", isRoom: true},
      { campus_id: campuses[0].campus_id, buildingName: "Main Building", floorName: "2nd Floor", roomName: "213", isRoom: true},
    ])

    console.log("Sample data inserted successfully!");


  } catch (error) {
    console.error("Error setting up sample data:", error);
  }
}

module.exports = InsertSampleData;
